name: 'Build and Deploy Production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js version to 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - name: Run Build production (create dist folder)
        run: npm run build

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-production
          path: dist

  deploy-to-production:
    needs: build-production-job
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-production
          path: dist

      - run:
          ls dist
          #ให้ Deploy เอง
      - uses: actions/checkout@v4

      - name: publish vue to github pages
        uses: SerhiiKa/VuePagesAction@1.0.4
        with:
          username: ${{ github.actor }}
          reponame: ${{ github.event.repository.name}}
          token: ${{ secrets.GITHUB_TOKEN}}
