name: 'Build and Deploy Production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js version to 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - name: Run Build production (create dist folder)
        run: npm run build

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist
